export const defaultFileIcon = "default-file";

export const specialFileMap: Record<string, string> = {
  "dockerfile": "docker",
  "docker-compose.yml": "docker",
  "docker-compose.yaml": "docker",
  "compose.yml": "docker",
  "compose.yaml": "docker",
  "makefile": "makefile-icon",
  "cmakelists.txt": "cmake",
  "jenkinsfile": "jenkins",
  "vagrantfile": "vagrant",
  "cargo.toml": "rust",
  "cargo.lock": "rust",
  "go.mod": "go",
  "go.sum": "go",
  "gemfile": "ruby",
  "gemfile.lock": "ruby",
  "rakefile": "ruby",
  "package.json": "js",
  "package-lock.json": "js",
  "tsconfig.json": "ts",
  "helmfile.yaml": "helm",
  "helmfile.yml": "helm",
  "chart.yaml": "helm",
  "chart.yml": "helm",
  "values.yaml": "helm",
  "kustomization.yaml": "kustomize",
  "kustomization.yml": "kustomize",
  "fluxfile.yaml": "flux",
  ".gitignore": "git",
  ".gitmodules": "git",
  ".gitattributes": "git",
  ".dockerignore": "docker",
  ".helmignore": "helm",
  ".env": "dotenv",
  ".env.local": "dotenv",
  ".env.development": "dotenv",
  ".env.production": "dotenv",
  ".env.test": "dotenv",
  ".env.example": "dotenv",
  "readme.md": "markdown",
  "changelog.md": "markdown",
  "license": "certificate",
  "license.md": "certificate",
  "license.txt": "certificate",
  ".eslintrc.json": "json",
  ".prettierrc": "json",
  "ansible.cfg": "ansible",
  "playbook.yml": "ansible",
  "playbook.yaml": "ansible",
  "prometheus.yml": "prometheus",
  "prometheus.yaml": "prometheus",
  "grafana.ini": "grafana",
  "nginx.conf": "nginx",
  "pom.xml": "maven",
  "build.gradle": "gradle",
  "build.gradle.kts": "gradle",
  "settings.gradle": "gradle",
  "bazel": "bazel",
  "build": "bazel",
  "workspace": "bazel",
};

export const extMap: Record<string, string> = {
  // Languages
  go: "go",
  py: "python",
  rb: "ruby",
  rs: "rust",
  java: "java",
  kt: "kotlin",
  kts: "kotlin",
  scala: "scala",
  swift: "swift",
  c: "c",
  h: "c",
  cpp: "cpp",
  cc: "cpp",
  cxx: "cpp",
  hpp: "cpp",
  cs: "csharp",
  php: "php",
  pl: "perl",
  pm: "perl",
  lua: "lua",
  r: "r",
  hs: "haskell",
  dart: "dart",
  ex: "elixir",
  exs: "elixir",
  erl: "erlang",
  ts: "ts",
  tsx: "ts",
  js: "js",
  jsx: "js",
  mjs: "js",
  cjs: "js",
  // Config
  yaml: "yaml",
  yml: "yaml",
  json: "json",
  jsonc: "json",
  json5: "json",
  toml: "toml",
  ini: "ini",
  cfg: "cfg",
  conf: "cfg",
  env: "dotenv",
  properties: "ini",
  tf: "terraform",
  tfvars: "terraform",
  hcl: "terraform",
  xml: "xml",
  // Web
  html: "html",
  htm: "html",
  css: "css",
  scss: "css",
  sass: "css",
  less: "css",
  vue: "vue",
  svelte: "svelte",
  // Data
  sql: "sql",
  csv: "csv",
  tsv: "csv",
  proto: "protobuf",
  graphql: "graphql",
  gql: "graphql",
  // Documents
  md: "markdown",
  mdx: "markdown",
  pdf: "pdf",
  doc: "docx",
  docx: "docx",
  xls: "xls",
  xlsx: "xlsx",
  ppt: "ppt",
  pptx: "pptx",
  txt: "txt",
  rtf: "txt",
  log: "log",
  // Shell
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  ps1: "powershell",
  bat: "powershell",
  cmd: "powershell",
  // Build
  gradle: "gradle",
  groovy: "gradle",
  // Archives
  zip: "zip",
  tar: "gz",
  gz: "gz",
  tgz: "gz",
  bz2: "gz",
  xz: "gz",
  deb: "deb",
  rpm: "deb",
  jar: "jar",
  war: "jar",
  // Images
  png: "png",
  jpg: "png",
  jpeg: "png",
  gif: "gif",
  svg: "png",
  ico: "png",
  webp: "png",
  // Crypto/certs
  pem: "pem",
  crt: "certificate",
  cer: "certificate",
  key: "pem",
  p12: "pem",
  pfx: "pem",
  // Other
  diff: "diff",
  patch: "diff",
  lock: "lock",
};

export function resolveFileTypeIcon(filename: string): string {
  if (!filename) return defaultFileIcon;
  const basename = filename.includes("/")
    ? filename.split("/").pop()!
    : filename;
  const lower = basename.toLowerCase();

  if (specialFileMap[lower]) return specialFileMap[lower];
  for (const [special, icon] of Object.entries(specialFileMap)) {
    if (lower.startsWith(special + ".") || lower === special) return icon;
  }

  const dotIdx = basename.lastIndexOf(".");
  if (dotIdx > 0) {
    const ext = basename.slice(dotIdx + 1).toLowerCase();
    if (extMap[ext]) return extMap[ext];
  }

  return defaultFileIcon;
}
